export type LocationEntry = {
  slug: string;
  city: string;
  state: "NC" | "VA";
  stateFull: string;
  county: string;
  blurb: string;
  nearby: string[];
  corridor: string;
  distanceNote: string;
};

export const locations: LocationEntry[] = [
  // North Carolina - Wake / Franklin / Nash county area around Zebulon
  {
    slug: "zebulon-nc",
    city: "Zebulon",
    state: "NC",
    stateFull: "North Carolina",
    county: "Wake County",
    blurb: "Home base for Under Pressure Xteriors, right in eastern Wake County.",
    nearby: ["Wendell", "Wake Forest", "Rolesville"],
    corridor: "US-264",
    distanceNote: "Local - this is where we're based.",
  },
  {
    slug: "wendell-nc",
    city: "Wendell",
    state: "NC",
    stateFull: "North Carolina",
    county: "Wake County",
    blurb: "A fast-growing Wake County town just down US-64 from Zebulon.",
    nearby: ["Zebulon", "Knightdale", "Raleigh"],
    corridor: "US-64",
    distanceNote: "Minutes from our home base in Zebulon.",
  },
  {
    slug: "knightdale-nc",
    city: "Knightdale",
    state: "NC",
    stateFull: "North Carolina",
    county: "Wake County",
    blurb: "One of the Triangle's fastest-growing suburbs, full of newer neighborhoods with a lot of exterior surface to maintain.",
    nearby: ["Wendell", "Raleigh", "Rolesville"],
    corridor: "US-64",
    distanceNote: "A short drive west of Zebulon.",
  },
  {
    slug: "rolesville-nc",
    city: "Rolesville",
    state: "NC",
    stateFull: "North Carolina",
    county: "Wake County",
    blurb: "A quickly developing town north of Knightdale with plenty of newer siding and driveways still under builder-grade sealant.",
    nearby: ["Wake Forest", "Zebulon", "Youngsville"],
    corridor: "NC-401",
    distanceNote: "Just north of Zebulon in Wake County.",
  },
  {
    slug: "wake-forest-nc",
    city: "Wake Forest",
    state: "NC",
    stateFull: "North Carolina",
    county: "Wake County",
    blurb: "A historic Wake County town with a mix of established brick homes and new construction throughout its growing subdivisions.",
    nearby: ["Rolesville", "Youngsville", "Raleigh"],
    corridor: "US-1",
    distanceNote: "Northwest of Zebulon, a straightforward drive.",
  },
  {
    slug: "youngsville-nc",
    city: "Youngsville",
    state: "NC",
    stateFull: "North Carolina",
    county: "Franklin County",
    blurb: "A small Franklin County town seeing rapid new-construction growth along the US-1 corridor.",
    nearby: ["Wake Forest", "Franklinton", "Rolesville"],
    corridor: "US-1",
    distanceNote: "Just over the Wake/Franklin county line from Zebulon.",
  },
  {
    slug: "franklinton-nc",
    city: "Franklinton",
    state: "NC",
    stateFull: "North Carolina",
    county: "Franklin County",
    blurb: "A Franklin County town with older housing stock that benefits from regular soft washing and gutter maintenance.",
    nearby: ["Youngsville", "Louisburg", "Bunn"],
    corridor: "US-1",
    distanceNote: "Northwest of Zebulon in Franklin County.",
  },
  {
    slug: "louisburg-nc",
    city: "Louisburg",
    state: "NC",
    stateFull: "North Carolina",
    county: "Franklin County",
    blurb: "The Franklin County seat, with a historic downtown and surrounding rural properties.",
    nearby: ["Franklinton", "Bunn", "Nashville"],
    corridor: "US-401",
    distanceNote: "North of Zebulon along the Franklin County line.",
  },
  {
    slug: "bunn-nc",
    city: "Bunn",
    state: "NC",
    stateFull: "North Carolina",
    county: "Franklin County",
    blurb: "A rural Franklin County community with farmhouses, larger lots, and outbuildings alongside newer homes.",
    nearby: ["Zebulon", "Louisburg", "Spring Hope"],
    corridor: "NC-39",
    distanceNote: "Northeast of Zebulon in Franklin County.",
  },
  {
    slug: "raleigh-nc",
    city: "Raleigh",
    state: "NC",
    stateFull: "North Carolina",
    county: "Wake County",
    blurb: "North Carolina's capital and the anchor of the Triangle, with everything from downtown storefronts to sprawling residential subdivisions.",
    nearby: ["Knightdale", "Garner", "Wake Forest"],
    corridor: "US-64 / I-540",
    distanceNote: "A straight shot west of Zebulon.",
  },
  {
    slug: "garner-nc",
    city: "Garner",
    state: "NC",
    stateFull: "North Carolina",
    county: "Wake County",
    blurb: "A growing Wake County town south of Raleigh with a strong mix of residential neighborhoods and commercial corridors.",
    nearby: ["Raleigh", "Clayton", "Knightdale"],
    corridor: "US-70",
    distanceNote: "South of Raleigh, a reasonable drive from Zebulon.",
  },
  {
    slug: "clayton-nc",
    city: "Clayton",
    state: "NC",
    stateFull: "North Carolina",
    county: "Johnston County",
    blurb: "One of the fastest-growing towns in the state, with new subdivisions going up constantly along the US-70 corridor.",
    nearby: ["Garner", "Smithfield", "Raleigh"],
    corridor: "US-70",
    distanceNote: "Southeast of Raleigh, within our regular service radius.",
  },
  {
    slug: "smithfield-nc",
    city: "Smithfield",
    state: "NC",
    stateFull: "North Carolina",
    county: "Johnston County",
    blurb: "The Johnston County seat, with a historic downtown and a wide mix of home ages and commercial buildings.",
    nearby: ["Clayton", "Selma", "Wilson's Mills"],
    corridor: "US-70 / I-95",
    distanceNote: "Southeast of Zebulon along the I-95 corridor.",
  },
  {
    slug: "nashville-nc",
    city: "Nashville",
    state: "NC",
    stateFull: "North Carolina",
    county: "Nash County",
    blurb: "The Nash County seat, a quiet community with established neighborhoods and a small-town commercial district.",
    nearby: ["Rocky Mount", "Bunn", "Spring Hope"],
    corridor: "US-64",
    distanceNote: "East of Zebulon toward Rocky Mount.",
  },
  {
    slug: "rocky-mount-nc",
    city: "Rocky Mount",
    state: "NC",
    stateFull: "North Carolina",
    county: "Nash / Edgecombe Counties",
    blurb: "A regional hub along I-95 with a broad mix of residential neighborhoods, retail centers, and industrial property.",
    nearby: ["Nashville", "Wilson", "Tarboro"],
    corridor: "I-95 / US-64",
    distanceNote: "East of Zebulon along US-64.",
  },
  {
    slug: "henderson-nc",
    city: "Henderson",
    state: "NC",
    stateFull: "North Carolina",
    county: "Vance County",
    blurb: "A Vance County city near Kerr Lake with a mix of lakefront properties and in-town residential and commercial buildings.",
    nearby: ["Oxford", "Louisburg", "South Hill, VA"],
    corridor: "I-85 / US-1",
    distanceNote: "North of Zebulon, near the Virginia state line.",
  },
  {
    slug: "oxford-nc",
    city: "Oxford",
    state: "NC",
    stateFull: "North Carolina",
    county: "Granville County",
    blurb: "The Granville County seat, with a historic downtown district and surrounding residential neighborhoods.",
    nearby: ["Henderson", "Butner", "Louisburg"],
    corridor: "NC-96",
    distanceNote: "Northwest of Zebulon toward the Virginia line.",
  },
  // Virginia - US-58 corridor / southern VA towns
  {
    slug: "south-hill-va",
    city: "South Hill",
    state: "VA",
    stateFull: "Virginia",
    county: "Mecklenburg County",
    blurb: "A Southside Virginia town along the US-58 corridor, just across the state line from our home base.",
    nearby: ["Clarksville", "Chase City", "Henderson, NC"],
    corridor: "US-58 / I-85",
    distanceNote: "The closest Virginia stop on our regular route.",
  },
  {
    slug: "clarksville-va",
    city: "Clarksville",
    state: "VA",
    stateFull: "Virginia",
    county: "Mecklenburg County",
    blurb: "A lake town on Kerr Lake / Buggs Island Lake, with waterfront homes and docks that see heavy algae and mildew exposure.",
    nearby: ["South Hill", "Chase City", "Boydton"],
    corridor: "US-58",
    distanceNote: "Along the US-58 corridor in Southside Virginia.",
  },
  {
    slug: "chase-city-va",
    city: "Chase City",
    state: "VA",
    stateFull: "Virginia",
    county: "Mecklenburg County",
    blurb: "A small Southside Virginia town with a historic core and surrounding rural residential properties.",
    nearby: ["South Hill", "Clarksville", "Kenbridge"],
    corridor: "US-58",
    distanceNote: "Southside Virginia, off the US-58 corridor.",
  },
  {
    slug: "emporia-va",
    city: "Emporia",
    state: "VA",
    stateFull: "Virginia",
    county: "Greensville County",
    blurb: "An independent city along I-95 in Southside Virginia, with a mix of residential neighborhoods and roadside commercial property.",
    nearby: ["South Hill", "Lawrenceville", "Jarratt"],
    corridor: "I-95 / US-58",
    distanceNote: "Southside Virginia along the I-95 corridor.",
  },
  {
    slug: "south-boston-va",
    city: "South Boston",
    state: "VA",
    stateFull: "Virginia",
    county: "Halifax County",
    blurb: "A Halifax County town along the US-58 corridor with a historic tobacco-district downtown and surrounding residential streets.",
    nearby: ["Danville", "Clarksville", "Chase City"],
    corridor: "US-58",
    distanceNote: "Southside Virginia, west along the US-58 corridor.",
  },
  {
    slug: "danville-va",
    city: "Danville",
    state: "VA",
    stateFull: "Virginia",
    county: "Pittsylvania County",
    blurb: "A larger Southside Virginia city on the North Carolina border, with historic river-district architecture and a wide residential and commercial base.",
    nearby: ["South Boston", "Yanceyville, NC", "Martinsville"],
    corridor: "US-58 / US-29",
    distanceNote: "The western edge of our Virginia service area.",
  },
];

export const getLocation = (slug: string) => locations.find((l) => l.slug === slug);
export const ncLocations = locations.filter((l) => l.state === "NC");
export const vaLocations = locations.filter((l) => l.state === "VA");
